steps:
- name: 'node'
  entrypoint: 'bash'
  args: ['-c', 'npm install && npm run build']
  dir: './frontend'  # Adjust this if your React app is in a subdirectory

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gsutil -m rsync -r build/ gs://e_attandance_frontend']
