name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Triggers the action when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login eattentanceazure.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t eattentanceazure.azurecr.io/backend:latest .

      - name: Tag Docker image
        run: |
          docker tag eattentanceazure.azurecr.io/backend:latest eattentanceazure.azurecr.io/backend:latest

      - name: Push Docker image to ACR
        run: |
          docker push eattentanceazure.azurecr.io/backend:latest
